# fly.toml app configuration file generated for wedding-site-server on 2023-11-02T16:15:50-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wedding-site-server"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
